version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:12.17.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "yarn installing" # run the `echo` command
      - run: yarn 
      - run: CI=true yarn build
  test:
    docker: 
      - image: circleci/node:12.17.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "testing stuff" # run the `echo` command
      - run: yarn
      - run: yarn test
  hithere:
    docker: 
      - image: circleci/node:12.17.0 
    steps:
      - checkout
      - run: echo "helloooooo!!!"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - build