version: 2.1
jobs:
  build1:
    docker: 
      - image: circleci/node:12.17.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "first build" # run the `echo` command
  build2:
    docker: 
      - image: circleci/node:12.17.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "second build" # run the `echo` command
workflows:
  version: 2
  build1_build2:
    jobs:
      -build1
      -build2